name: 'build-test'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn run all
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: pull_request_author
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Get the username
        run: echo "The author was ${{ steps.pull_request_author.outputs.author }}"
